[package]
name = "chewing-internal"
version = "0.5.1-alpha.1"
edition = "2021"

[dependencies]
chewing = { version = "0.5.1-alpha.1", path = ".." }

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.23.0"
