[package]
name = "chewing-internal"
description = "Internal C API for the Chewing (酷音) intelligent Zhuyin input method."
license = "LGPL-2.1-or-later"
version = "0.5.1-alpha.1"
edition = "2021"

[dependencies]
chewing = { version = "0.5.1-alpha.1", path = ".." }
ffi-opaque = "2.0.0"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.24.3"
